CREATE TYPE sensor_type AS ENUM (
  'FRONT_LIDAR',
  'FRONT_ULTRASONIC',
  'REAR_ULTRASONIC',
  'WHEEL_SPEED',
  'GPS_LOCATION',
  'GPS_SPEED',
  'GPS_DIRECTION',
  'MAGNETOMETER_DIRECTION'
);

ALTER TYPE sensor_type RENAME VALUE 'FRONT_LIDAR' TO 'DISTANCE_LIDAR';
ALTER TYPE sensor_type RENAME VALUE 'FRONT_ULTRASONIC' TO 'DISTANCE_ULTRASONIC';
ALTER TYPE sensor_type RENAME VALUE 'REAR_ULTRASONIC' TO 'GPS';
ALTER TYPE sensor_type RENAME VALUE 'GPS_additional';
ALTER TYPE sensor_type RENAME VALUE 'GPS_LOCATION' TO 'SPEED_FRONT_LEFT';
ALTER TYPE sensor_type RENAME VALUE 'GPS_SPEED' TO 'SPEED_FRONT_RIGHT';
ALTER TYPE sensor_type RENAME VALUE 'GPS_DIRECTION' TO 'SPEED_REAR_LEFT';
ALTER TYPE sensor_type RENAME VALUE 'MAGNETOMETER_DIRECTION' TO 'SPEED_REAR_RIGHT';

